import React from 'react';

const PrivacyPolicy = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      <h1 className="text-3xl font-semibold mb-6">Privacy Policy for MLBB Tournament Signup Form</h1>
      <p className="text-lg mb-4">Last updated: December 27, 2024</p>
      
      <section>
        <h2 className="text-2xl font-semibold mb-4">Privacy Policy</h2>
        <p className="mb-4">
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p className="mb-4">
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Free Privacy Policy Generator.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold mb-4">Interpretation and Definitions</h2>
        <h3 className="text-xl font-semibold mb-2">Interpretation</h3>
        <p className="mb-4">
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.
        </p>

        <h3 className="text-xl font-semibold mb-2">Definitions</h3>
        <p className="mb-2"><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
        <p className="mb-2"><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
        <p className="mb-2"><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to MLBB Tournament Signup Form.</p>
        <p className="mb-2"><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
        <p className="mb-2"><strong>Country</strong> refers to: Philippines.</p>
        <p className="mb-2"><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
        <p className="mb-2"><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
        <p className="mb-2"><strong>Service</strong> refers to the Website.</p>
        <p className="mb-2"><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</p>
        <p className="mb-2"><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
        <p className="mb-2"><strong>Website</strong> refers to MLBB Tournament Signup Form, accessible from https://vp-tournamentform.vercel.app/</p>
        <p className="mb-2"><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold mb-4">Collecting and Using Your Personal Data</h2>
        <h3 className="text-xl font-semibold mb-2">Types of Data Collected</h3>
        <h4 className="text-lg font-semibold mb-2">Personal Data</h4>
        <p className="mb-4">
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
        </p>
        <ul className="list-disc list-inside mb-4">
          <li>Email address</li>
          <li>Phone number</li>
          <li>Usage Data</li>
        </ul>

        <h4 className="text-lg font-semibold mb-2">Usage Data</h4>
        <p className="mb-4">
          Usage Data is collected automatically when using the Service.
        </p>
        <p className="mb-4">
          Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
        </p>

        <h4 className="text-lg font-semibold mb-2">Tracking Technologies and Cookies</h4>
        <p className="mb-4">
          We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
        </p>
        <ul className="list-disc list-inside mb-4">
          <li>Cookies or Browser Cookies. A cookie is a small file placed on Your Device.</li>
          <li>Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons.</li>
        </ul>
        <p className="mb-4">
          We use both Session and Persistent Cookies for the purposes set out below:
        </p>

        <ul className="list-disc list-inside mb-4">
          <li><strong>Necessary / Essential Cookies</strong>: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.</li>
          <li><strong>Cookies Policy / Notice Acceptance Cookies</strong>: These Cookies identify if users have accepted the use of cookies on the Website.</li>
          <li><strong>Functionality Cookies</strong>: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference.</li>
        </ul>
      </section>

      <section>
        <h2 className="text-2xl font-semibold mb-4">Use of Your Personal Data</h2>
        <p className="mb-4">
          The Company may use Personal Data for the following purposes:
        </p>
        <ul className="list-disc list-inside mb-4">
          <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
          <li>To manage Your Account.</li>
          <li>For the performance of a contract.</li>
          <li>To contact You.</li>
          <li>To provide You with news, special offers, and general information about other goods, services, and events.</li>
          <li>For business transfers.</li>
          <li>For other purposes such as data analysis, identifying usage trends, and evaluating the effectiveness of promotional campaigns.</li>
        </ul>
      </section>

      <section>
        <h2 className="text-2xl font-semibold mb-4">Retention of Your Personal Data</h2>
        <p className="mb-4">
          The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold mb-4">Transfer of Your Personal Data</h2>
        <p className="mb-4">
          Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold mb-4">Delete Your Personal Data</h2>
        <p className="mb-4">
          You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold mb-4">Disclosure of Your Personal Data</h2>
        <p className="mb-4">
          The Company may disclose Your Personal Data under certain circumstances, such as in business transactions or law enforcement situations.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold mb-4">Security of Your Personal Data</h2>
        <p className="mb-4">
          The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet is 100% secure.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold mb-4">Children's Privacy</h2>
        <p className="mb-4">
          Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold mb-4">Links to Other Websites</h2>
        <p className="mb-4">
          Our Service may contain links to other websites that are not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold mb-4">Changes to This Privacy Policy</h2>
        <p className="mb-4">
          We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
        </p>
      </section>
    </div>
  );
};

export default PrivacyPolicy;
